name: Lint

on:
  push:
    branches: [$default-branch]
  pull_request:
  workflow_dispatch:

jobs:
  setup_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.1'

      - name: Set yarn version
        run: yarn set version 1.22.21

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Check Formatting
        run: yarn prettier --check .
